# Generated by Django 5.0.7 on 2024-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('poster', models.URLField(max_length=300)),
                ('rated', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=250)),
                ('plot', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
